# Generated by Django 4.2.1 on 2023-06-04 13:01

from django.db import migrations, models
import utils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assents/favicon/%Y/%m/', validators=[utils.model_validators.validade_png]),
        ),
    ]
